In [3]:
#Создаем соединение с SQL (+создаем ввод пароля)
import psycopg2
import getpass

conn = psycopg2.connect(user='postgres', 
                        database='postgres', 
                        host='localhost', 
                        port='5433', 
                        password = getpass.getpass('Insert password: ')
                       )
print(conn.get_dsn_parameters())

Insert password: ········
{'user': 'postgres', 'dbname': 'postgres', 'host': 'localhost', 'port': '5433', 'tty': '', 'options': '', 'sslmode': 'prefer', 'sslcompression': '0', 'krbsrvname': 'postgres', 'target_session_attrs': 'any'}

In [131]:
#Получение данных
#Нам необходимы следующие данные: ISIN, тип купона (постоянный и дисконтный), столбец, указывающий, является ли 
#облигация амортизационной, купон, его дата платежа, цена и дата обратного выкупа по оферете,
#купонный период, номинальная стоимость, дата погашения облигации
#Из всего пречисленного нас особо интересуют непогашенные облигации, также убираем отсутствующие значения ISIN
import pandas as pd
query="SELECT DISTINCT public.bond_description.\"ISIN, RegCode, NRDCode\", public.bond_description.\"CouponType\", \
            public.bond_description.\"AmortisedMty\", \
            public.quotes.\"CPN\", public.quotes.\"BUYBACKDATE\", \
            public.quotes.\"BUYBACKPRICE\", \
            public.quotes.\"CPN_DATE\", public.quotes.\"CPN_PERIOD\", \
            public.quotes.\"FACEVALUE\", public.quotes.\"MAT_DATE\" \
            FROM public.bond_description INNER JOIN public.quotes \
            ON public.quotes.\"ISIN\" = public.bond_description.\"ISIN, RegCode, NRDCode\"  \
            WHERE \"ISIN, RegCode, NRDCode\" IS NOT NULL AND \"MAT_DATE\" > current_date AND (\"CouponType\" = 'Постоянный' OR \"CouponType\" = 'Дисконт');"
data=pd.read_sql_query(query, conn)
data

,"ISIN, RegCode, NRDCode",CouponType,AmortisedMty,CPN,BUYBACKDATE,BUYBACKPRICE,CPN_DATE,CPN_PERIOD,FACEVALUE,MAT_DATE
0,RU000A0JS6Z2,Постоянный,False,55.1500,None,None,2014-10-21,183.0,1000.00,2022-04-27
1,RU000A0JV3M2,Постоянный,True,51.3700,None,None,2015-07-29,125.0,1000.00,2019-12-24
2,RU000A0JUP63,Постоянный,False,0.7400,None,None,2014-12-18,182.0,10.00,2019-12-12
3,RU000A0JUBA1,Постоянный,False,20.8200,None,None,2015-03-03,91.0,1000.00,2020-11-24
4,RU000A0JUP63,Постоянный,False,0.7400,None,None,2015-12-17,182.0,10.00,2019-12-12
5,RU000A0JVUM4,Постоянный,False,57.0433,None,None,2016-04-14,182.0,1000.00,2035-09-20
6,RU000A0JV3M2,Постоянный,True,37.3973,None,None,2015-10-28,91.0,1000.00,2019-12-24
7,RU000A0JUVT9,Постоянный,False,NaN,None,None,2015-04-08,NaN,1000.00,2021-09-29
8,RU000A0JUVT9,Постоянный,False,49.8630,None,None,2016-04-06,182.0,1000.00,2021-09-29
9,RU000A0JVFE2,Постоянный,False,77.2877,None,None,2015-12-01,182.0,1000.00,2020-11-24
10,RU000A0JU5W7,Постоянный,False,37.4000,None,None,2014-11-25,182.0,1000.00,2021-05-18
11,RU000A0JTYA5,Постоянный,False,31.9100,None,None,2013-12-04,182.0,1000.00,2020-05-27
12,RU000A0JTYA5,Постоянный,False,31.9100,None,None,2014-12-03,182.0,1000.00,2020-05-27
13,RU000A0JS6Z2,Постоянный,False,55.1500,None,None,2015-10-22,183.0,1000.00,2022-04-27
14,RU000A0JU5W7,Постоянный,False,NaN,None,None,2014-05-27,NaN,1000.00,2021-05-18
15,RU000A0JUBA1,Постоянный,False,20.8200,None,None,2015-06-02,91.0,1000.00,2020-11-24
16,RU000A0JUBA1,Постоянный,False,20.8178,None,None,2015-12-01,91.0,1000.00,2020-11-24
17,RU000A0JV102,Постоянный,False,NaN,None,None,2015-06-04,NaN,0.01,2020-05-28
18,RU000A0JU5W7,Постоянный,False,37.4000,None,None,2015-05-26,182.0,1000.00,2021-05-18
19,RU000A0JV3M2,Постоянный,True,NaN,None,None,2015-04-29,NaN,1000.00,2019-12-24
20,RU000A0JVUB7,Постоянный,False,64.8219,None,None,2016-04-08,182.0,1000.00,2020-10-02
21,RU000A0JV102,Постоянный,False,NaN,None,None,2015-06-04,182.0,0.01,2020-05-28
22,RU000A0JV3M2,Постоянный,True,51.3700,None,None,2015-04-29,125.0,1000.00,2019-12-24
23,RU000A0JUVT9,Постоянный,False,49.8600,None,None,2015-04-08,182.0,1000.00,2021-09-29
24,RU000A0JUVT9,Постоянный,False,49.8600,None,None,2015-10-07,182.0,1000.00,2021-09-29
25,RU000A0JV102,Постоянный,False,0.0009,None,None,2015-12-03,182.0,0.01,2020-05-28
26,RU000A0JS6Z2,Постоянный,False,55.1507,None,None,2015-10-22,183.0,1000.00,2022-04-27
27,RU000A0JTYA5,Постоянный,False,31.9123,None,None,2015-12-02,182.0,1000.00,2020-05-27
28,RU000A0JUBA1,Постоянный,False,20.8200,None,None,2014-09-02,91.0,1000.00,2020-11-24
29,RU000A0JU5W7,Постоянный,False,37.3973,None,None,2015-11-24,182.0,1000.00,2021-05-18
...,...,...,...,...,...,...,...,...,...,...
43,RU000A0JVKC6,Постоянный,True,NaN,None,None,2015-12-29,NaN,1000.00,2020-06-23
44,RU000A0JUP63,Постоянный,False,0.7405,None,None,2015-12-17,182.0,10.00,2019-12-12
45,RU000A0JS6Z2,Постоянный,False,55.1500,None,None,2015-04-22,183.0,1000.00,2022-04-27
46,RU000A0JUTB1,Постоянный,False,24.3100,None,None,2015-06-04,91.0,1000.00,2029-08-16
47,RU000A0JVUB7,Постоянный,False,NaN,None,None,None,NaN,1000.00,2020-10-02
48,RU000A0JUBA1,Постоянный,False,20.8200,None,None,2015-09-01,91.0,1000.00,2020-11-24
49,RU000A0JV3M2,Постоянный,True,37.4000,None,None,2015-07-29,91.0,1000.00,2019-12-24
50,RU000A0JUTB1,Постоянный,False,24.3100,None,None,2015-12-03,91.0,1000.00,2029-08-16
51,RU000A0JUBA1,Постоянный,False,NaN,None,None,2014-03-04,NaN,1000.00,2020-11-24
52,RU000A0JS6Z2,Постоянный,False,NaN,None,None,2012-10-19,NaN,1000.00,2022-04-27
53,RU000A0JUP63,Постоянный,False,0.7400,None,None,2015-06-18,182.0,10.00,2019-12-12
54,RU000A0JUBA1,Постоянный,False,20.8200,None,None,2015-12-01,91.0,1000.00,2020-11-24
55,RU000A0JUBA1,Постоянный,False,20.8200,None,None,2014-03-04,91.0,1000.00,2020-11-24
56,RU000A0JTYA5,Постоянный,False,31.9100,None,None,2015-12-02,182.0,1000.00,2020-05-27
57,RU000A0JUP63,Постоянный,False,NaN,None,None,2014-12-18,NaN,10.00,2019-12-12
58,RU000A0JV3M2,Постоянный,True,37.4000,None,None,2015-10-28,91.0,1000.00,2019-12-24
59,RU000A0JUTB1,Постоянный,False,NaN,None,None,2014-12-04,NaN,1000.00,2029-08-16
60,RU000A0JVUB7,Постоянный,False,NaN,None,None,2016-04-08,NaN,1000.00,2020-10-02
61,RU000A0JUBA1,Постоянный,False,20.8200,None,None,2014-12-02,91.0,1000.00,2020-11-24
62,RU000A0JUBA1,Постоянный,False,20.8200,None,None,2014-06-03,91.0,1000.00,2020-11-24
63,RU000A0JS6Z2,Постоянный,False,55.1500,None,None,2012-10-19,183.0,1000.00,2022-04-27
64,RU000A0JV102,Постоянный,False,NaN,None,None,2015-12-03,182.0,0.01,2020-05-28
65,RU000A0JTYA5,Постоянный,False,31.9100,None,None,2014-06-04,182.0,1000.00,2020-05-27
66,RU000A0JU5W7,Постоянный,False,37.4000,None,None,2014-05-27,182.0,1000.00,2021-05-18
67,RU000A0JVKC6,Постоянный,True,65.2700,None,None,2015-12-29,182.0,1000.00,2020-06-23
68,RU000A0JUTB1,Постоянный,False,24.3082,None,None,2015-12-03,91.0,1000.00,2029-08-16
69,RU000A0JVUM4,Постоянный,False,NaN,None,None,2016-04-14,NaN,1000.00,2035-09-20
70,RU000A0JVFE2,Постоянный,False,77.2900,None,None,2015-12-01,182.0,1000.00,2020-11-24
71,RU000A0JS6Z2,Постоянный,False,55.1500,None,None,2013-04-20,183.0,1000.00,2022-04-27
72,RU000A0JTYA5,Постоянный,False,31.9100,None,None,2015-06-03,182.0,1000.00,2020-05-27

In [119]:
#Используем следуюшие аргументы: ISIN, дата, логин
def my_fun(ISIN, RegCode, NRDCode,date, db_login):
    conn=psycopg2.connect(user=db_login['user'],
                      database=db_login['database'],
                      host=db_login['host'],
                      port=db_login['port'],
                      password=getpass.getpass('Insert password: '))

#дальше ничего пока не получилось (но я пыталась)

In [132]:
 data.pivot_table(index='ISIN, RegCode, NRDCode', columns='CPN_DATE', values='CPN')

CPN_DATE,2012-10-19,2013-04-20,2013-10-20,2013-12-04,2014-03-04,2014-04-21,2014-05-27,2014-06-03,2014-06-04,2014-09-02,...,2015-12-01,2015-12-02,2015-12-03,2015-12-17,2015-12-29,2016-01-27,2016-04-06,2016-04-08,2016-04-14,2016-04-22
"ISIN, RegCode, NRDCode",,,,,,,,,,,,,,,,,,,,,
RU000A0JS6Z2,55.15,55.15,55.15,NaN,NaN,55.15,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,55.1507
RU000A0JTYA5,NaN,NaN,NaN,31.91,NaN,NaN,NaN,NaN,31.91,NaN,...,NaN,31.91115,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RU000A0JU5W7,NaN,NaN,NaN,NaN,NaN,NaN,37.4,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RU000A0JUBA1,NaN,NaN,NaN,NaN,20.82,NaN,NaN,20.82,NaN,20.82,...,20.81890,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RU000A0JUP63,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.74025,NaN,NaN,NaN,NaN,NaN,NaN
RU000A0JUTB1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,24.3091,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RU000A0JUVT9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,49.863,NaN,NaN,NaN
RU000A0JV102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0009,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RU000A0JV3M2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,37.3973,NaN,NaN,NaN,NaN
RU000A0JVFE2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,77.28885,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RU000A0JVKC6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,65.27035,NaN,NaN,NaN,NaN,NaN
RU000A0JVUB7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64.8219,NaN,NaN
RU000A0JVUM4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57.0433,NaN